name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install make deps
        run: |
          sudo apt install texlive-latex-extra

      - name: make
        run: |
          make -C catppuccinpalette ctan
          make -C beamercolorthemecatppuccin ctan

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            catppuccinpalette/catppuccinpalette-ctan.zip
            catppuccinpalette/build/unpacked/catppuccinpalette.sty
            beamercolorthemecatppuccin/beamercolorthemecatppuccin-ctan.zip
            beamercolorthemecatppuccin/build/unpacked/beamercolorthemecatppuccin.sty
